VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsOpportunityOfferBudgetTpl"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "6-DOMINIO-Oportunidades y compresores.d-Ofertas.Plantillas"
Option Explicit

Private Const MODULE_NAME As String = "clsOpportunityOfferBudgetTpl"


